### ISSUE TITLE
Open Source Project.

### ISSUE THREAD

**Issue by 0vg** [m4tex/project-eleos#1]
Dear Sir/Madam,

I am writing to express my interest in your project and to inquire if I may be of assistance. I am currently working on a college project that involves contributing to an open source project, and I believe that your project would be an excellent opportunity to further my skills and knowledge.

May I inquire if you are currently active in development and if there are any ways I can help? I am very eager to learn more about your project and would appreciate any information you can provide.

Thank you for your time and consideration, and I look forward to hearing from you soon.

Sincerely,
Mark

**Comment by m4tex** [comment]
Hi, nice to hear that you got interested in my project. Unfortunately, my hand-in date for this project is tomorrow and four programmers no longer maintain the project but me. After the hand-in date, the texture and model designers probably won't be of assistance and since I'm graduating this year I won't be working on this myself for at least a month until I graduate.
